### ISSUE TITLE
error codes msgs in windows version

### ISSUE THREAD

**Issue by mro1337** [klamonte/qodem#7] opened 2016-03-19 15:32 UTC
http://i.imgur.com/QdvXhZI.png

**Comment by mro1337** [comment] 2016-03-19 15:33
getting them all over the place

**Comment by klamonte** [comment] 2016-03-19 16:43
Thank you for reporting this. I will dig into it. Is this Windows 7 or a different version?

**Comment by mro1337** [comment] 2016-03-19 18:31
i am running windows 7 64 bit and receive this error. let me know if you want to trouble shoot this.


----- Original Message -----

**Comment by klamonte** [comment] 2016-03-21 02:22
I just tried it in a Win7-64 VM and it didn't emit the error messages.  Hmm.

So the message itself is coming about because Qodem is trying to map a keystroke input it received from PDcurses to a string to send to the other side, and it could not find an appropriate string to send.  More specifically, ansi_keystroke() in source/ansi.c is returning NULL at the bottom.  The best solution would be to figure out what pdcurses_key() in source/input.c is seeing that is being passed to ansi_keystroke() that is not being found.  Another not-as-good alternative is to suppress the message, but then there is a good chance that the error will instead be that you are hitting keys on the keyboard that should be doing something but instead are doing nothing.

Would you be OK with running a debug build to help see this?  I can make one tomorrow and attach it here.

**Comment by mro1337** [comment] 2016-03-21 05:07
yup. let me know when it's ready and link it.

---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by klamonte** [comment] 2016-03-21 22:06
I was able to reproduce this, and just put a new Windows install image out.  Try this one out, does it fix things for you?

Direct link: http://qodem.sourceforge.net/qodem-1.0beta-preview-setup.exe

**Comment by mro1337** [comment] 2016-03-22 21:57
just tried it out and it works great.

---
This email has been checked for viruses by Avast antivirus software.
https://www.avast.com/antivirus

**Comment by klamonte** [comment] 2016-03-22 23:40
Awesome, thank you!  Closing this one out.

**Closed by klamonte** 2016-03-22 23:40 UTC
