### ISSUE TITLE
Segmentation fault in terminal emulators with high column count

### ISSUE THREAD

**Issue by Slider-Whistle** [klamonte/qodem#78] opened 2018-12-23 00:11 UTC
When running qodem through a terminal emulator in X qodem consistently has a segmentation fault when launched in a terminal of exactly 159 columns or more. Expanding a terminal to this size while the program is running doesn't crash it immediately, but it does crash when the next command is issued.

If this isn't reproducible, I'll post my configuration and a log if I can figure it out.

**Comment by klamonte** [comment] 2018-12-25 15:18
Thanks for reporting this.  I am not able to reproduce with either master or 1.0.1-dev branch.

Which distro and X terminal are you using?

**Comment by Slider-Whistle** [comment] 2018-12-26 04:34
I'm using the 1.0.0 release on Slackware 14.2. My window manager is [dwm](http://dwm.suckless.org/). but I don't think the tiling would be a cause since the same happens in floating mode. I've tested xterm,. uxterm, and st, and the issue seems to effect all of them.
I built the program from source, so if nobody can reproduce it, that probably means I just screwed that up somehow.

These are the options I've changed from the default in qodemrc:
editor = vim
status_line = false
80_columns = false (this could be an issue)

**Comment by klamonte** [comment] 2019-02-22 15:31
Are you by chance using Qodem with mouse-supporting applications when it crashes?  I just remembered another special "160 column" case: that happens to be the exact column number at which non-UTF-8 X10 mouse coordinates can generate an invalid UTF-8 code point.

**Comment by Slider-Whistle** [comment] 2019-02-23 10:57
Nope, Qodem crashes before it's able to open the "Phone Book". Is there some other way a bug like that could stop the program from working properly? I do use UTF-8, but I'm not sure whether that'd be relevant.

**Comment by klamonte** [comment] 2022-02-08 22:32
Moving to GitLab...

**Closed by klamonte** 2022-02-08 22:32 UTC
